In [7]:
import numpy as np

In [9]:
print("****1.Dot Product****")
x=np.array([1,2,3])
y=np.array([4,5,6])
dot_product=np.dot(x,y)
print("Dot product:",dot_product)

print("*****2.Cross Product*****")
x=np.array([1,2,3])
y=np.array([4,5,6])
cross_product=np.cross(x,y)
print("Cross product:",cross_product)

print("*****3.Matrix Multiplication*****")
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
matrix_product=np.matmul(x,y)
print("Matrix product:\n",matrix_product)

print("*****4.Inverse of a matrix*****")
x=np.array([[1,2],[3,4]])
inverse_matrix=np.linalg.inv(x)
print("Inverse of matrix:\n",inverse_matrix)

print("****Tranpose of a matrix****")
x=np.array([[1,2],[3,4]])
transpose_matrix=np.transpose(x)
print("Transpose of matrix:\n",transpose_matrix)

print("*****5.Eigenvalues and Eigenvectors*****")
x=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(x)
print("Eigenvalues:",eigenvalues)
print("Eigenvectors:\n",eigenvectors)

print("*****6.Determinant of a matrix*****")
x=np.array([[1,2],[3,4]])
determinant=np.linalg.det(x)
print("Determinant of matrix:",determinant)

print("*****7.Matrix addition and subtraction*****")
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
addition=x+y
subtraction=x-y
print("Matrix addition:\n",addition)
print("Matrix subtraction:\n",subtraction)

print("\n -----Solve Linear Equations-----")
# 2x + y = 5
# x + y = 3
A = np.array([[2,1],
              [1,1]])
B = np.array([5, 3])

solution = np.linalg.solve(x,y)
print(solution)


****1.Dot Product****
Dot product: 32
*****2.Cross Product*****
Cross product: [-3  6 -3]
*****3.Matrix Multiplication*****
Matrix product:
 [[19 22]
 [43 50]]
*****4.Inverse of a matrix*****
Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
****Tranpose of a matrix****
Transpose of matrix:
 [[1 3]
 [2 4]]
*****5.Eigenvalues and Eigenvectors*****
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
*****6.Determinant of a matrix*****
Determinant of matrix: -2.0000000000000004
*****7.Matrix addition and subtraction*****
Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix subtraction:
 [[-4 -4]
 [-4 -4]]

 -----Solve Linear Equations-----
[[-3. -4.]
 [ 4.  5.]]
